export const apiKey = 'a92c5e88d76346de956173028240512';

export const weatherImages = {
    'Sunny': require('../assets/weatherImages/sunny.png'),
    'Clear': require('../assets/weatherImages/clear.png'),
    'Partly cloudy': require('../assets/weatherImages/partly-cloudy.png'),
    'Partly Cloudy ': require('../assets/weatherImages/partly-cloudy.png'),
    'Partly Cloudy': require('../assets/weatherImages/partly-cloudy.png'),
    'Cloudy': require('../assets/weatherImages/cloudy.png'),
    'Cloudy ': require('../assets/weatherImages/cloudy.png'),
    'Overcast': require('../assets/weatherImages/cloudy.png'),
    'Overcast ': require('../assets/weatherImages/cloudy.png'),
    'Mist': require('../assets/weatherImages/mist.png'),
    'Patchy rain possible': require('../assets/weatherImages/rain-light.png'),
    'Patchy snow possible': require('../assets/weatherImages/sun-rain-snow.png'),
    'Patchy sleet possible': require('../assets/weatherImages/sleet.png'),
    'Patchy freezing drizzle possible': require('../assets/weatherImages/sun-rain-snow.png'),
    'Thundery outbreaks possible': require('../assets/weatherImages/lightning-sun.png'),
    'Blowing snow': require('../assets/weatherImages/snowstorm.png'),
    'Blizzard': require('../assets/weatherImages/snow-snow.png'),
    'Fog': require('../assets/weatherImages/mist.png'),
    'Freezing fog': require('../assets/weatherImages/mist.png'),
    'Patchy light drizzle': require('../assets/weatherImages/rain-light-light-light.png'),
    'Light drizzle': require('../assets/weatherImages/rain-light.png'),
    'Freezing drizzle': require('../assets/weatherImages/sleet.png'),
    'Heavy freezing drizzle': require('../assets/weatherImages/sleet.png'),
    'Patchy light rain': require('../assets/weatherImages/day-rain.png'),
    'Light rain': require('../assets/weatherImages/rain-light.png'),
    'Moderate rain at times': require('../assets/weatherImages/rain-heavy.png'),
    'Moderate rain': require('../assets/weatherImages/rain-heavy.png'),
    'Heavy rain at times': require('../assets/weatherImages/sun-rain.png'),
    'Heavy rain': require('../assets/weatherImages/heavy-heavy-heavy-rain.png'),
    'Light freezing rain': require('../assets/weatherImages/sleet.png'),
    'Moderate or heavy freezing rain': require('../assets/weatherImages/sleet.png'),
    'Light sleet': require('../assets/weatherImages/sleet.png'),
    'Moderate or heavy sleet': require('../assets/weatherImages/sleet.png'),
    'Patchy light snow': require('../assets/weatherImages/snowflake.png'),
    'Light snow': require('../assets/weatherImages/snowflake.png'),
    'Patchy moderate snow': require('../assets/weatherImages/snowflake.png'),
    'Moderate snow': require('../assets/weatherImages/snowflake.png'),
    'Patchy heavy snow': require('../assets/weatherImages/snow-snow.png'),
    'Heavy snow': require('../assets/weatherImages/snow-snow.png'),
    'Ice pellets': require('../assets/weatherImages/ice.png'),
    'Light rain shower': require('../assets/weatherImages/rain-light.png'),
    'Moderate or heavy rain shower': require('../assets/weatherImages/rain-heavy.png'),
    'Torrential rain shower': require('../assets/weatherImages/heavy-heavy-heavy-rain.png'),
    'Light sleet showers': require('../assets/weatherImages/sleet.png'),
    'Moderate or heavy sleet showers': require('../assets/weatherImages/sleet.png'),
    'Light snow showers': require('../assets/weatherImages/snowflake.png'),
    'Moderate or heavy snow showers': require('../assets/weatherImages/snowflake.png'),
    'Light showers of ice pellets': require('../assets/weatherImages/ice.png'),
    'Moderate or heavy showers of ice pellets': require('../assets/weatherImages/ice.png'),
    'Patchy light rain with thunder': require('../assets/weatherImages/lightning-sun.png'),
    'Moderate or heavy rain with thunder': require('../assets/weatherImages/lightning.png'),
    'Patchy light snow with thunder': require('../assets/weatherImages/lightning-clod.png'),
    'Moderate or heavy snow with thunder': require('../assets/weatherImages/lightning-lightning-cloud.png'),
    'Patchy rain nearby': require('../assets/weatherImages/rain-light.png'),
}